layout_spectrum: 0.2636949
typography_spectrum: 0.8899033
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.424812
  brandColors:
    - '#171738'
    - '#F3E080'
    - '#C6AC7F'
    - '#A33931'
    - '#E08839'
  rhythmicContrast: 0.7524167
name: Savory and Sweets Catering
