collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7524167
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#0E0D0C'
    - '#FFFFFC'
    - '#876D67'
    - '#C8C5BC'
  rhythmicContrast: 0.245435
typography_spectrum: 0.8899033
layout_spectrum: 0.2733619
name: Savory and Sweets Catering
